feat(periodic):add perdiodic cron job

diff --git a/integration-tests/cron-jobs/periodic-cron-job.yaml b/integration-tests/cron-jobs/periodic-cron-job.yaml
--- a/integration-tests/cron-jobs/periodic-cron-job.yaml
+++ b/integration-tests/cron-jobs/periodic-cron-job.yaml
@@ -24,11 +24,34 @@ spec:
                   export KONFLUX_SCENARIO_NAME="konflux-ui-periodic-main"
                   export KONFLUX_TENANT_NAME="konflux-ui-tenant"
                   export KONFLUX_APPLICATION_NAME="konflux-ui"
-                  export KONFLUX_COMPONENT_NAME="konflux-ui"                  
+                  export KONFLUX_COMPONENT_NAME="konflux-ui"
 
-                  echo -e "[INFO] Triggering test scenario ${KONFLUX_SCENARIO_NAME}"
+                  echo -e "[INFO] Fetching latest snapshot from ${KONFLUX_TENANT_NAME} related to push events."
 
-                  kubectl -n "${KONFLUX_TENANT_NAME}" test.appstudio.openshift.io/run="${KONFLUX_SCENARIO_NAME}"
+                  LATEST_SNAPSHOT=$(kubectl get snapshots -n "${KONFLUX_TENANT_NAME}" -o json | \
+                      jq --arg application "$KONFLUX_APPLICATION_NAME" --arg component "$KONFLUX_COMPONENT_NAME" -r '
+                          .items
+                          | map(select(
+                              .metadata.labels."appstudio.openshift.io/application" == $application and
+                              .metadata.labels."appstudio.openshift.io/component" == $component and
+                              .metadata.labels."pac.test.appstudio.openshift.io/event-type" == "push" and
+                              (.status.conditions // [] | map(select(
+                                  .type == "AutoReleased" and
+                                  .reason == "AutoReleased" and
+                                  .status == "True"
+                                  ))
+                              | length > 0)
+                              ))
+                          | sort_by(.metadata.creationTimestamp) | last | .metadata.name')
+
+                  if [[ -z "${LATEST_SNAPSHOT}" || "${LATEST_SNAPSHOT}" == "null" ]]; then
+                    echo -e "[ERROR] No valid snapshot found. The job will not be triggered."
+                    exit 1
+                  fi
+
+                  echo -e "[INFO] Triggering test scenario ${KONFLUX_SCENARIO_NAME} from snapshot ${LATEST_SNAPSHOT}."
+
+                  kubectl -n "${KONFLUX_TENANT_NAME}" label snapshot "${LATEST_SNAPSHOT}" test.appstudio.openshift.io/run="${KONFLUX_SCENARIO_NAME}"
 
                   echo "[INFO] Integration Service E2E tests successfully triggered!"
           restartPolicy: Never
